Add a link to the GitHub repo
ioxio-dataspace/example-app pull request #11
Opened 2024-04-12 03:29 UTC by omarudolley

Add a link to the GitHub repo from the app itself.  `pnpm install` updated the lock file.

<img width="700" alt="latest_link" src="https://github.com/ioxio-dataspace/example-app/assets/58733599/0ed89cf8-1753-4115-8e2c-a2a8d37249e6">

2024-04-12 08:03 UTC, meandrewandyou commented on frontend/src/index.css
> +.nav-link {
Does this styles affects anything?

2024-04-12 08:04 UTC, meandrewandyou approved these changes
Asked one question.

2024-04-12 08:09 UTC, omarudolley commented on frontend/src/index.css
> +.nav-link {
with <img width="515" alt="Screenshot 2024-04-12 110717" src="https://github.com/ioxio-dataspace/example-app/assets/58733599/8ccd553b-f1fc-40cd-a6df-e12e6024b4a2"> vs without 
<img width="553" alt="Screenshot 2024-04-12 110751" src="https://github.com/ioxio-dataspace/example-app/assets/58733599/aaa91338-bc50-43e4-84ab-e10b53dd12a3">

2024-04-17 07:41 UTC, TheHelias approved these changes

2024-04-19 09:32 UTC, fbjorn approved these changes

2024-04-22 08:09 UTC, lietu commented on frontend/src/assets/github.svg
Has anyone actually looked with their eyeballs at this image?

2024-04-22 08:09 UTC, lietu requested changes
Replace the GitHub image with a proper one

2024-04-22 08:20 UTC, omarudolley commented on frontend/src/assets/github.svg
We should update this also https://github.com/ioxiocom/ioxio-docs/blob/main/src/lib/images/github.svg

2024-04-22 08:36 UTC, lietu commented on frontend/src/assets/github.svg
Yes, please do

2024-04-22 11:50 UTC, lietu commented on frontend/src/components/Navbar.jsx
> +        <img className="nav-logo" src={github} alt="View source in GitHub" />
```suggestion
import GitHubLogo from "../assets/github.svg"

export default function Navbar() {
  return (
    <div className="nav">
      <a
        className="nav-link"
        href="https://github.com/ioxio-dataspace/example-app"
        rel="noreferrer"
        target="_blank"
      >
        <img className="nav-logo" src={GitHubLogo} alt="View source in GitHub" />
```

2024-04-22 11:51 UTC, lietu approved these changes

2024-04-22 11:51 UTC, merged